// Manually pick out encouraging quotes from GET request according to index
const validIndices = [
    8, // "Life is a learning experience, only if you learn."
    9, // "Self-complacency is fatal to progress."
    35, // "One fails forward toward success."
    47, // "He is able who thinks he is able."
    77, // "Faith in oneself is the best and safest course."
    90, // "Victory belongs to the most persevering."
    94, // "You can do it if you believe you can!"
    95, // "Set your goals high, and don't stop till you get there."
    112, // "The harder you fall, the higher you bounce."
    122, // "If you can dream it, you can do it."
    177, // "Our strength grows out of our weaknesses."
    183, // "Fortune favours the brave."
    197, // "You're never a loser until you quit trying."
    218, // "Either you run the day or the day runs you."
    223, // "Patience is the companion of wisdom."
    249, // "If there is no struggle, there is no progress."
    374, // "Don't be afraid to go out on a limb. That's where the fruit is."
    389, // "It does not matter how slowly you go as long as you do not stop."
    581, // "If you focus on results, you will never change. If you focus on change, you will get results."
    739, // "Memory is the mother of all wisdom."
    746, // "Action will remove the doubts that theory cannot solve."
    752, // "Accept challenges, so that you may feel the exhilaration of victory."
    773, // "Man cannot discover new oceans unless he has the courage to lose sight of the shore."
    779, // "There are no failures. Just experiences and your reactions to them."
    834, // "Fear of failure is one attitude that will keep you at the same point in your life."
    926, // "Anything you really want, you can attain, if you really go after it."
    933, // "Believe deep down in your heart that you're destined to do great things."
    993, // "A jug fills drop by drop."
    1003, // "Only those who dare to fail greatly can ever achieve greatly."
    1026, // "It can't be spring if your heart is filled with past failures."
    1037, // "A gem cannot be polished without friction, nor a man perfected without trials."
    1070, // "Excellence is not a skill. It is an attitude."
    1182, // "The greatest barrier to success is the fear of failure."
    1184, // "If you aren't going all the way, why go at all?"
    1225, // "Failure doesn't mean you are a failure it just means you haven't succeeded yet."
    1373, // "There is nothing impossible to him who will try."
    1400, // "The only real mistake is the one from which we learn nothing."
    1431, // "Your attitude, not your aptitude, will determine your altitude."
    1559, // "Success is determined by those whom prove the impossible, possible."
    1630 // "Nothing will work unless you do."
];